pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "274199249793"
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password') 
    } */
    // Build
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'AWS-AUTH', region: "${env.REGION}") {
                        sh """
                            cd Sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'AWS-AUTH', region: "${env.REGION}") {
                        sh """
                            cd Sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'AWS-AUTH', region: "${env.REGION}") {
                        sh """
                            cd Sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion EKS ACM ALB') {
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        script {
                            build job: 'Bastion', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: 'Eks', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }
                }
                stage('ACM') {
                    steps {
                        script {
                            build job: 'Acm', 
                            propagate: false,  // even SG fails VPC will not be effected
                            wait: false // VPC will not wait for SG pipeline completion
                        }
                    }  
                }
            }
        }
        stage('Trigger ALB') {
            steps {
                script {
                    build job: 'Frontend-Alb', 
                    propagate: false,  // even SG fails VPC will not be effected
                    wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }

        
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}